source/Frutin/Frutin/Controllers/HomePartial/_FooterPartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;

namespace Frutin.Controllers
{
    public class _FooterPartialController : Controller
    {
        // GET: _FooterPartial
        public ActionResult Index()
        {
            FooterContent model;
            using (UnitGenericRepository db = new UnitGenericRepository())
            {
                model = db.FooterContentRepository.Get(where:f=>f.IsAviable==true).FirstOrDefault();
            }
                return PartialView(model);
        }
    }
}

source/Frutin/Frutin/Controllers/HomePartial/_HeaderPartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;

namespace Frutin.Controllers
{
    public class _HeaderPartialController : Controller
    {
        // GET: _HeaderPartial 
        public ActionResult Index()
        {
            IEnumerable<HeaderMenu> menu;

            using (UnitGenericRepository db = new UnitGenericRepository())
            {
                ViewBag.notificationText = db.HeaderNotificationRepository.Get(where: n => n.IsAviable == true).Select(n => n.Text).First();
                menu = db.HeaderMenuRepository.Get(includes: "ChildHeaderMenus").ToList();
            }
            return PartialView(menu);
        }
    }
}

source/Frutin/Frutin/Views/Shared/_FrutinLayout.cshtml
<!DOCTYPE html>

<html class="no-js" lang="zxx" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewBag.title</title>
    <meta name="author" content="Frutin">
    <meta name="description" content="Frutin - Organic and Healthy Food HTML Template">
    <meta name="keywords" content="Frutin - Organic and Healthy Food HTML Template">
    <meta name="robots" content="INDEX,FOLLOW">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="Content/Refrence/img/favicons/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="apple-touch-icon" sizes="57x57" href="Content/Refrence/img/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="Content/Refrence/img/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="Content/Refrence/img/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="Content/Refrence/img/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="Content/Refrence/img/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="Content/Refrence/img/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="Content/Refrence/img/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="Content/Refrence/img/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="Content/Refrence/img/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="Content/Refrence/img/favicons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="Content/Refrence/img/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="Content/Refrence/img/favicons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="Content/Refrence/img/favicons/favicon-16x16.png">
    <link rel="manifest" href="Content/Refrence/img/favicons/manifest.json">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,100;9..40,200;9..40,300;9..40,400;9..40,500;9..40,600;9..40,700&family=Lexend:wght@300;400;500;600;700;800;900&family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="Content/Refrence/css/fontawesome.min.css">
    <link rel="stylesheet" href="Content/Refrence/css/magnific-popup.min.css">
    <link rel="stylesheet" href="Content/Refrence/css/swiper-bundle.min.css">
    <link rel="stylesheet" href="Content/Refrence/css/style.css">
    @*<link rel="stylesheet" href="Content/Refrence/css/bootstrap.min.css">*@
    @*<link href="~/Content/Refrence/custom/bootstrap.css" rel="stylesheet" />*@
    <link href="~/Content/Refrence/custom/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Refrence/custom/CustomStyle.css" rel="stylesheet" />
    @RenderSection("link", required: false)
</head>
<body>
    <header>
        @Html.Action("Index", "_HeaderPartial")
        @RenderSection("header", required: false)
    </header>
    <div>
        @RenderBody()
        <div class="scroll-top show">
            <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
                <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" style="transition: stroke-dashoffset 10ms linear; stroke-dasharray: 307.919, 307.919; stroke-dashoffset: 284.566;">
                </path>
            </svg>
        </div> @* Scrolbar *@
    </div>
    <footer>
        @Html.Action("Index", "_FooterPartial")
        @RenderSection("footer", required: false)
    </footer>
    <script src="~/Content/Refrence/js/vendor/jquery-3.6.0.min.js"></script>
    <script src="~/Content/Refrence/js/swiper-bundle.min.js"></script>
    <script src="~/Content/Refrence/js/bootstrap.min.js"></script>
    <script src="~/Content/Refrence/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/Refrence/js/jquery.counterup.min.js"></script>
    <script src="~/Content/Refrence/js/jquery-ui.min.js"></script>
    <script src="~/Content/Refrence/js/imagesloaded.pkgd.min.js"></script>
    <script src="~/Content/Refrence/js/isotope.pkgd.min.js"></script>
    <script src="~/Content/Refrence/js/main.js"></script>
    <script src="~/Content/Refrence/custom/bootstrap.js"></script>
    <script src="~/Content/Refrence/custom/bootstrap.min.js"></script>
    @* for _SubscribePartial post action *@
    <script>
        $(document).on("submit", "#newsletterForm", function (e) {
            e.preventDefault(); // جلوگیری از رفتار پیش‌فرض فرم

            $.ajax({
                url: $(this).attr("action"),
                method: "POST",
                data: $(this).serialize(),
                success: function (response) {
                    // رندر Partial View جدید در div
                    $("#newsletterPartial").html(response);
                    alert("عملیات با موفقیت انجام شد");
                },
                error: function () {
                    alert("خطایی رخ داده است. لطفاً دوباره تلاش کنید.");
                }
            });
        });
    </script>

    @RenderSection("script", required: false)
</body>
</html>

source/Frutin/Frutin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Refrence/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Refrence/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>